### ISSUE TITLE
[BUG] Typst webapp throws unknown "source sans 3" font family

### ISSUE THREAD

**Issue by cakeforcat** [DeveloperPaul123/modern-cv#80] opened 2024-11-11 14:49 UTC
![image](https://github.com/user-attachments/assets/e4438ac6-0860-4289-bfae-2df69a1ba2b5)
as seen in the above screenshot.

According to the instructions, besides awesome fonts, no further installation is necessary.

**Comment by DeveloperPaul123** [comment] 2024-11-11 14:58
I can't reproduce this. I just created a new project using `modern-cv:0.7.0` and I could not generate that warning. The web app may actually be using local fonts on your system now. I'm not sure if things have changed. If you don't want to install them on your computer, you can download the fonts from the provided links in the README and then in your typst project, create a `fonts` folder in the root and dump all the OTF files in that folder like you would for Fontawesome.

**Comment by DeveloperPaul123** [comment] 2024-11-11 15:54
What happens if you open this? https://typst.app/project/waIqyMEFbw_x8U2zpYaMEB

**Comment by cakeforcat** [comment] 2024-11-11 16:00
![image](https://github.com/user-attachments/assets/0efbcc97-5071-488a-a1f0-0b369aa5e17d)

**Comment by cakeforcat** [comment] 2024-11-11 16:01
It is easy to work around this by just inserting these fonts into the fonts folder, but it's weird why it's only these 3 and not Roboto for example

**Comment by DeveloperPaul123** [comment] 2024-11-11 16:03
> It is easy to work around this by just inserting these fonts into the fonts folder, but it's weird why it's only these 3 and not Roboto for example

Can you check your system fonts? Do you have Roboto installed and not the other fonts?

**Comment by cakeforcat** [comment] 2024-11-11 16:05
> Can you check your system fonts? Do you have Roboto installed and not the other fonts?

I do not have Roboto installed, and installing "Source Sans 3 - Regular" did not change anything unfortunately

**Comment by DeveloperPaul123** [comment] 2024-11-14 02:43
I still can't reproduce this, even in the web app
![image](https://github.com/user-attachments/assets/20d5ad1b-73f3-4bb7-bfb0-12bf0963ac1c)

To be clear @cakeforcat, is this warning causing any visible issues with rendering the template?

**Comment by cakeforcat** [comment] 2024-11-14 11:44
> To be clear @cakeforcat, is this warning causing any visible issues with rendering the template?
It seems to work just fine, as in I can't see a difference before/after adding the font to the fonts folder.
This might be some more annoying underlying typst webapp issue

**Comment by DeveloperPaul123** [comment] 2024-11-14 12:56
> > To be clear @cakeforcat, is this warning causing any visible issues with rendering the template?
> 
> It seems to work just fine, as in I can't see a difference before/after adding the font to the fonts folder. This might be some more annoying underlying typst webapp issue

Ok at least it doesn't cause issues. Honestly, I don't see a way to fix this without removing mention of the font from the template, but I don't think that is necessary. I'm going to close this for now.

**Closed by DeveloperPaul123** 2024-11-14 12:56 UTC
Labels: bug

**Comment by mgrimace** [comment] 2025-02-14 16:03
Interestingly enough, I have this same issue on a new install on MacOS. I installed the fonts locally via download and install via Mac Fontbook, but it's showing the same error. The output appears just fine, but FYI
